services:
  # Java development environment
  java-dev:
    image: myproject/java:latest
    container_name: java-development
    volumes:
      # Mount current directory
      - .:/workspace
      # Mount the setup script
      - ./setup-plugins.sh:/setup-plugins.sh:ro
      # Java-specific workspace
      - ./java-projects:/workspace/java-projects
      # Maven cache to speed up builds
      - maven-cache:/root/.m2
      # Persist vim and tmux configs
      - java-vim-config:/root/.vim
      - java-config:/root
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9000:9000"  # Debug port
    stdin_open: true
    tty: true
    working_dir: /workspace/java-projects

  # Zig development environment
  zig-dev:
    image: myproject/zig:latest
    container_name: zig-development
    volumes:
      # Mount current directory
      - .:/workspace
      # Mount the setup script
      - ./setup-plugins.sh:/setup-plugins.sh:ro
      # Zig-specific workspace
      - ./zig-projects:/workspace/zig-projects
      # Persist vim and tmux configs
      - zig-vim-config:/root/.vim
      - zig-config:/root
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    stdin_open: true
    tty: true
    working_dir: /workspace/zig-projects

volumes:
  maven-cache:
  java-vim-config:
  java-config:
  zig-vim-config:
  zig-config: